# Site settings
# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://huruifeng.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

#relative_permalinks: false
# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
title: Learning, Running, Travelling


brand: Ruifeng Hu
headline: Dedicated to Rigorous Science to Make a Better World !

# Short description of your site
description: Daliy life of Ruifeng Hu

copyright: Rufieng Hu  •  2017  •  huruifeng.github.io.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
phone: +1-979-264-7270
email: huruifeng.cn@hotmail.com

# Fill in your Google Analytics ID to track your website using GA
googleAnalitycsID: UA-102009333-1

homephoto: xiao.jpg

author:
  name : Ruifeng Hu
  email : huruifeng.cn@hotmail
  github : huruifeng
  facebook : huruifeng
  linkedin : huruifeng
  SinaWB : hrflove99

#permalink: /:year-:month-:day-:title/
permalink: /:title.html

plugins:
  - jekyll-paginate
paginate: 30

sass:
  sass_dir: assets/css